(() => {
    console. log('Hello world!');
  
    //const buttonPieces = document.querySelectorAll(".button-image"),
      //    dropZones = document.querySelector(".animal");
  
  
      setTimeout(function(){
         mainHeading.textContent = "Let's Play Instruments!";
           mainHeading.classList.add("selected");
      },1000);
  
  
  //    function logID(){
    //  console.log('clicked on a graphic -  this one: ', this.id);
    //   this.classList.add('selected');
  //  }
  
  
  var dropTarget = document.querySelector(".animal-box");
  var draggables = document.querySelectorAll(".button-image");
  
  for (let i = 0; i < draggables.length; i++) {
    draggables[i].addEventListener("dragstart", function(event){
        event.dataTransfer.setData("srcId", event.target.id);
    });
  
  }
  
  dropTarget.addEventListener("dragover", function(event){
    event.preventDefault();
  });
  
  dropTarget.addEventListener("drop", function(event){
    event.preventDefault();
    stopPlaying();
    let target = event.target;
    let srcId = event.dataTransfer.getData("srcId");
    // console.log(document.getElementById(srcId), 'srcId')
    const dataKey = document.getElementById(srcId).getAttribute("data-key");
    // target.appendChild(document.getElementById(srcId));
    target.setAttribute('data-play', dataKey);
    playAllInstruments();
  });
  
  function stopPlaying() {
    var animalBox = document.getElementsByClassName("animal-box");
    let animals = animalBox[0].children;
  
    for (var i = 0; i < animals.length; i++) {
      let sound = document.querySelector(`audio[data-key="${animals[i].getAttribute("data-play")}"]`);
  
      if (sound) {
        sound.pause();
        sound.currentTime = 0;
      }
    }
  }
  
    function playAllInstruments() {
      var animalBox = document.getElementsByClassName("animal-box");
      let animals = animalBox[0].children;
      // console.log('wololo', animals);
  
      for (var i = 0; i < animals.length; i++) {
        let sound = document.querySelector(`audio[data-key="${animals[i].getAttribute("data-play")}"]`);
  
        if (sound) {
          sound.currentTime = 0;
          sound.play();
        }
      }
  
    }
  
  function playMatchingAudio(event) {
  
    // console.log('I am here', event.target)
    //play the card match game
    //card 1 is the keyboard keyCode (generated by the keypress event)
  
    // let card1 = event.target.getAttribute("data-key");
    let card1 = event.keyCode;
    //keyCode is html's data-key
  
    // take card1 (the keyCode) and find the matching audio element
    // // using the custom data-key attribute
    let card2 = document.querySelector(`audio[data-key="${card1}"]`),
    musicButtons = document.querySelector(`img[data-key="${card1}"]`);
    //both same
    // console.log('I am here', card2)
  
  // ! tests for a negative result
  // falsy means something can understand or it can be null
    if (!card2) {return;}
  
    card2.currentTime = 0;
    card2.play();
  
    musicButtons.classList.add('playing');
    // if you have a match, play card2 (the matching audio element)
    //if (card2) {
      // rewind the audio sound first
      //card2.currentTime = 0;
      //card2.play();
    //}
    //debugger
  }
  
    window.addEventListener('musicButtonsdown', playMatchingAudio);
  
    // var elements = document.getElementsByClassName("button-image");
  
    // for (var i = 0; i < elements.length; i++) {
    //   elements[i].addEventListener('click', playMatchingAudio, false);
    // }
  
  
    //function changeImageSet() {
    // change all the image elements on the page -> draggable image sources,
    //imageNames. forEach((piece, index) => {
  //  buttonPieces[index].src = `images/${piece + this.dataset.key}.jpg`;
    //});
   //debugger;
  //}
  
      //function allowDrag(event){
      //console.log('started dragging an image: this one - ', event.target.id);
      //event.dataTransfer.setData('draggedImg', this.id);}
      //event.dataTransfer.setData("targetTrack", this.dataset.track);
    //}
      //function allowDragOver(event){
    //  event.preventDefault();
    //  console.log('dragged something over me!');
    //  }
  
    //  function allowDrop(event){
    //  console.log('dropped something on me!');
    //  let droppedImage = event.dataTransfer.getData('draggedImg');
    //  if(event.currentTarget.children.length !== 0) {
  
      //  let currentButtonPiece = event.currentTarget.children[0];
      //  let currentDropZone = event.currentTarget;
  
      //  let audio = document.querySelector(`audio[data-sound="${currentButtonPieces.id}]"`)
  
      //  audio.pause();
      //  audio.currentTime = 0;
  
        //reset current audio
      // currentButtonPiece = currentZone.removeChild(currentButtonPiece);
  
    //  }
  
    //  event.currentTarget.appendChild(document.querySelector(`#${droppedImage}`));
    //  let audio = document.querySelector(`audio[data-sound="${droppedImage}"]`)
  
      // if(!audio){return;}
      /// audio.currentTime = 0;
    //   audio.loop = true;
    //   audio.play();
    // }
  
    // for(let zone of dropZones){
    //    zone.addEventListener('dragover',allowDragOver);
    //    zone.addEventListener('drop',allowDrop);
    // }
  
  //buttonPieces.forEach(piece => piece.addEventListener('dragstart', allowDrag));
  
  
  
  
  })();
  